### ISSUE TITLE
Add Let's Go Pikachu/Eevee new moves

### ISSUE THREAD

**Issue by jalyna** [jalyna/oakdex-pokedex#119]

**Comment by haykam821** [comment]
For Partner Pikachu:

* Zippy Zap
* Splishy Splash
* Floaty Fall

For Partner Eevee:

* Bouncy Bubble
* Buzzy Buzz
* Sizzly Slide
* Glitzy Glow
* Baddy Bad
* Sappy Seed
* Freezy Frost
* Sparkly Swirl
