### ISSUE TITLE
Rubygem and Node Package both return nil/null

### ISSUE THREAD

**Issue by Shwheelz** [jalyna/oakdex-pokedex#54]
I'm having this issue with both the Ruby and Node versions of oakdex.  No matter what I call, I always just get null back.

![oakdex](https://cloud.githubusercontent.com/assets/7189274/26756699/259a76f2-486e-11e7-9910-a1e95117a560.PNG)

**Comment by Shwheelz** [comment]
```
var oakdex = require('oakdex-pokedex');
oakdex.findPokemon(number, function(p) {
            console.log(p.names.en);
});
// cannot read property 'names' of undefined
```

**Comment by jalyna** [comment]
@Shwheelz Please try again for the ruby gem (release 0.1.3). It should work now. Thanks for reporting the bug!

I will further investigate in the node package.

**Comment by Shwheelz** [comment]
The rubygem is working great now, thanks!  I'm still having trouble with the node package though.  I'm trying to call within an Alexa skill, so it's admittedly hard to debug.  But following your example, I have 

```
let prepareQuestions = function(pokemonList) {
    let questionList = [];
    for (let pokemon of pokemonList) {
        Oakdex.findPokemon(pokemon, function(p) {
            let types = p.types;      // This is the error line below (index.js:43:26)
            questionList.push({question: pokemon, answer: types})
        });
    }
    
    return questionList;
}
```

Here's the stack trace; perhaps it could be useful.  I'll continue to poke around as I get time as well, and maybe we can solve this.  I this your node package is really useful, and I'm hoping to get it to work so I can make Alexa skills with it in the future.

```
module initialization error: TypeError
    at /var/task/index.js:43:26
    at /var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:106:13
    at /var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:47:5
    at allByName (/var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:9:5)
    at pokemonById (/var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:43:3)
    at /var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:103:9
    at allByName (/var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:9:5)
    at Object.findPokemon (/var/task/node_modules/oakdex-pokedex/src/oakdex_pokedex.js:100:5)
    at prepareQuestions (/var/task/index.js:41:16)
    at Object.<anonymous> (/var/task/index.js:51:22)
```

**Comment by Shwheelz** [comment]
It appears all your node packages are passing, so I'm going to close the issue until I have ample time to debug my own app.  Thanks again for fixing the Rubygem though!  Great work!
