### ISSUE TITLE
Include Alolan forms as variations

### ISSUE THREAD

**Issue by fvitale** [jalyna/oakdex-pokedex#55]
I expect to find under (as an example)
```
> Oakdex::Pokedex::Pokemon.find('Vulpix').variations
 => [] 
```
the alolan form information. Is this going to be added? Thank you!

**Comment by guilhermegirao** [comment]
Hello, I'm working on it, maybe today or tomorrow I'll end. :smile:

**Comment by fvitale** [comment]
Thank you! I am just using a small % of the info the gem provide, but you can take a look https://github.com/fvitale/pokemon_types
I added a thank you in the readme
